######  Python  ###########
# if you did this in Python, single file, accounts

.PHONY : build view clean

build :
	chmod +x accounts

view :
	@less accounts

#This isn't need as python does not produce a binary
clean :
	@\rm *.pyc
		
